Feature/services-adaptive
Team-Code-Wizards/frontend pull request #120
Opened 2024-01-26 17:58 UTC by darikomarenko

Добавила адаптив для блока Услуги. Изменила стили Услуги для разрешения 1440 (убрала лишние nth-of). 
Для проверки убрала все остальные компоненты из main, чтобы общий фон не мешал проверять по пп, так как у этого блока общий фон с другими, которые еще не готовы.
<img width="515" alt="Снимок экрана 2024-01-26 в 20 44 23" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/8e46ec77-af8f-4c84-9890-4deab7adaa4c">
<img width="515" alt="Снимок экрана 2024-01-26 в 20 45 13" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/097041ab-60b0-4a68-bd78-4a7ab51b3ead">

2024-01-27 19:51 UTC, EkaterinaYurchyk2022 commented on src/app/globals.scss
> +  --involve-font: "Involve";
дубль строк

2024-01-27 19:51 UTC, EkaterinaYurchyk2022 commented on src/app/globals.scss
> +    sans-serif;
дубль строк

2024-01-27 19:52 UTC, EkaterinaYurchyk2022 commented on src/app/globals.scss
> +      var(--involve-font),
в конце строчек точка с запятой ( ; )

2024-01-27 19:54 UTC, EkaterinaYurchyk2022 commented on src/app/globals.scss
> +  );
дубль

2024-01-27 19:54 UTC, EkaterinaYurchyk2022 commented on src/app/globals.scss
> +  );
дубль

2024-01-27 19:55 UTC, EkaterinaYurchyk2022 commented on src/app/globals.scss
> +  // === Font Sizes ===
этого уже нет

2024-01-27 20:08 UTC, EkaterinaYurchyk2022 requested changes
не сошёлся по ПП. Когда сверяем,ширину экрана берём 1440px - 1280px - 834px - 390px, а ширина контента внутреннего - 1280px - 1024px - 768px - 320px соответственно. Неактуальный global.scss

2024-01-27 20:10 UTC, EkaterinaYurchyk2022 requested changes
Не прикрепила фото:
![Услуги390](https://github.com/Team-Code-Wizards/frontend/assets/98664770/1e189201-9d60-4ce1-9505-cdaebd0fe550)
![Услуги834](https://github.com/Team-Code-Wizards/frontend/assets/98664770/3a6342f4-af9e-48a6-86ec-57767e0e4c37)
![Услуги1280](https://github.com/Team-Code-Wizards/frontend/assets/98664770/1eb3521f-9883-4872-8dd2-5bc1f96de28c)
![Услуги1440](https://github.com/Team-Code-Wizards/frontend/assets/98664770/9acc630e-7c19-48ba-99f6-ca40e5d26fea)

2024-01-28 05:44 UTC, darikomarenko commented on src/app/globals.scss
> +      var(--involve-font),
дубли, походу, из-за мержда случились, а точки с запятой отсутствующие тоже не мои, но я поправлю

2024-01-28 07:36 UTC, darikomarenko commented
Исправила недочёты, залила с фоном. Пока не прям по пп, потому что на макетах в разном порядке блоки, а они шириной по содержимому, особенно на мобилке видно. Но работает и меняется по макету

2024-01-28 15:17 UTC, OGSmit reviewed
![чччччч](https://github.com/Team-Code-Wizards/frontend/assets/114614095/e33d6591-570c-4f39-b827-4c8bdc8be7ac)

между брейкпоинтами верстка должна быть более продуманной

2024-01-28 15:17 UTC, OGSmit commented on src/components/Services/style.module.scss
> +        background-color: #b3b9fc;
сделать плавную анимацию при наведении

2024-01-28 15:17 UTC, OGSmit commented on src/components/Services/style.module.scss
> +  }
сделай с помощью grid , ограничивай ячейки по размеру ( 1fr , ...) , контент внутри ячеек сделай на 100% ширины

2024-01-28 15:17 UTC, OGSmit commented on src/components/Services/style.module.scss
>  .service-card {
карточку не стоит ограничивать по высоте , высота элемента состоит из отступов + контента

2024-01-28 15:17 UTC, OGSmit commented on src/components/Services/style.module.scss
> +  }
между брэйкпоинтами прилипает к левому краю заголовок

2024-01-30 16:25 UTC, closed without merging