Feature/promo-adaptive
Team-Code-Wizards/frontend pull request #122
Opened 2024-01-27 15:47 UTC by EkaterinaYurchyk2022

[https://github.com/orgs/Team-Code-Wizards/projects/1/views/1?pane=issue&itemId=50754186](url)
Сделан адаптив страницы Promo для всех размеров экранов, применены стили для адаптива, немного подкорректированы первоначальные стили, которые не совпадали с ПП измененного макета Figma, добавлены дополнительные брейк-поинты.

- 1440px
![1440](https://github.com/Team-Code-Wizards/frontend/assets/98664770/75ece5e6-193b-4faa-8397-47a96365567a)

- 1280px
![1280](https://github.com/Team-Code-Wizards/frontend/assets/98664770/eac27c0e-d06c-4275-b1eb-2f870d6892f6)

- 834px
![834](https://github.com/Team-Code-Wizards/frontend/assets/98664770/b5dd6b99-0825-4d54-8535-b93d23387b46)

- 390px
![390](https://github.com/Team-Code-Wizards/frontend/assets/98664770/1cf79c4b-66bf-4b87-850f-594b42f6ea0b)

2024-01-27 20:26 UTC, tintinelle commented on src/components/Promo/PromoForm/styles.module.scss
>  		font-family: var(--involve-font);
можно убрать, шрифт применяется в глобал

2024-01-27 20:28 UTC, tintinelle commented on src/components/Promo/PromoForm/styles.module.scss
> +		margin-top: -4px;
могу ошибаться, но вроде отрицательные марджины и паддинги - не очень хорошая практика (123 и 128 строки)

2024-01-27 20:30 UTC, tintinelle commented on src/components/Promo/styles.module.scss
> +	background-image: url('../../../public/images/promo/promo-bg.png');
нет необходимости прописывать относительный путь, можно просто начиная с /images , у тебя не работает так?

2024-01-27 20:34 UTC, tintinelle commented on src/components/Promo/styles.module.scss
> +			gap:89px
нет точки с запятой, может поломать что то)

2024-01-27 20:40 UTC, EkaterinaYurchyk2022 commented on src/components/Promo/styles.module.scss
> +	background-image: url('../../../public/images/promo/promo-bg.png');
нет,так не работает
и &/images тоже не работает

2024-01-27 20:40 UTC, tintinelle reviewed
У меня не сошлось по пп в 1440, 834 (немного перенос слов) и 390
Я вижу твои скрины, и что у тебя все сошлось, не знаю, почему у меня так выглядит. Посмотрела на двух браузерах специально. Пусть кто то еще посмотрит у себя
<img width="684" alt="Снимок экрана 2024-01-28 в 01 10 06" src="https://github.com/Team-Code-Wizards/frontend/assets/104452692/85303cbd-59fc-4b5e-8c61-1049b2340b41">
<img width="539" alt="Снимок экрана 2024-01-28 в 01 13 25" src="https://github.com/Team-Code-Wizards/frontend/assets/104452692/1ab968a7-a560-44c8-8f4a-c6d24aa25262">
<img width="369" alt="Снимок экрана 2024-01-28 в 01 14 23" src="https://github.com/Team-Code-Wizards/frontend/assets/104452692/ca57e284-b7e5-4d29-b0f3-27885c1bed6f">

2024-01-27 20:41 UTC, EkaterinaYurchyk2022 commented on src/components/Promo/PromoForm/styles.module.scss
>  		font-family: var(--involve-font);
убрала

2024-01-27 20:43 UTC, EkaterinaYurchyk2022 commented on src/components/Promo/styles.module.scss
> +			gap:89px
да,спасибо)

2024-01-27 20:43 UTC, tintinelle commented on src/components/Promo/styles.module.scss
> +	background-image: url('../../../public/images/promo/promo-bg.png');
странно, у меня в других компонентах отображает( и твою ветку я стянула к себе, запустила, и у меня виден фон

2024-01-28 06:12 UTC, darikomarenko requested changes
у меня тоже к пп даже не близко(( в коде ошибки не нашла
<img width="639" alt="Снимок экрана 2024-01-28 в 09 04 47" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/8b1617ee-a11c-4d46-9c22-6fb2ead6e946">
<img width="614" alt="Снимок экрана 2024-01-28 в 09 09 52" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/22e3fb72-9d39-4bb6-bf61-ca41b97691f2">
<img width="601" alt="Снимок экрана 2024-01-28 в 09 10 44" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/934f1f9b-55e7-4d99-9dac-4683c04e503a">

<img width="791" alt="Снимок экрана 2024-01-28 в 09 02 54" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/95b98cf5-3450-4b52-a06d-8fddea1dbd8f">

2024-01-30 07:46 UTC, darikomarenko reviewed
У меня все еще не сходится форма, скрины прикрепляю(  хотя в целом все красиво уменьшается и выглядит красиво)
И еще на 391 резко меняется шрифт на более крупный (скрин тоже приложу) - видимо, меняется уже на планшетный, но он еще великоват для этого экрана, может, менять его чуть позже? ближе к 700
<img width="236" alt="Снимок экрана 2024-01-30 в 10 37 03" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/b3b96260-2ab2-475d-b420-5f1c7f930a99">
<img width="207" alt="Снимок экрана 2024-01-30 в 10 38 12" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/d9967b36-ed9f-42f0-919a-060e7897ee0c">
<img width="566" alt="Снимок экрана 2024-01-30 в 10 39 37" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/3e0fa349-a0ba-42cb-9af3-7117d3396e0f">
<img width="804" alt="Снимок экрана 2024-01-30 в 10 40 18" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/c08cb26d-1ef8-4c13-86f3-2f65003b8d32">

2024-01-30 13:39 UTC, natanchik reviewed
У меня сильно не сошлось ПП на 834 и 390.
Хорошо бы применить наборы шрифтов, там, где совпадает.

![Screenshot 2024-01-30 193203](https://github.com/Team-Code-Wizards/frontend/assets/79564962/4199ae99-7e9b-4f36-9e17-dce920923222)
![Screenshot 2024-01-30 193447](https://github.com/Team-Code-Wizards/frontend/assets/79564962/f8b3a318-87c4-48e5-8716-6c4404f1d260)

2024-01-30 16:40 UTC, OGSmit approved these changes

2024-01-31 05:55 UTC, natanchik approved these changes
По ПП все сошлось 👍

2024-01-31 06:03 UTC, darikomarenko approved these changes

2024-01-31 06:11 UTC, merged