Feature/guarantee-hover
Team-Code-Wizards/frontend pull request #205
Opened 2024-02-25 07:47 UTC by darikomarenko

Добавила hover на карточки Гарантии, удалила пустой файл interface.
<img width="1007" alt="Снимок экрана 2024-02-25 в 10 42 29" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/bada5f99-79d9-4297-96bc-9521cb2c4275">

2024-02-25 16:35 UTC, Govard9 commented
Баг: отсутвствет транзишн (узнала у Саши он должен быть .3s)
![image](https://github.com/Team-Code-Wizards/frontend/assets/63837534/a46e4a1c-22dc-4187-8b98-a738b7598e2e)

2024-02-25 16:38 UTC, Govard9 approved these changes

2024-02-27 11:56 UTC, EkaterinaMarkin requested changes
Отсутствует плавное появление в анимации (3000 мс)
<img width="619" alt="Снимок экрана 2024-02-27 в 14 48 43" src="https://github.com/Team-Code-Wizards/frontend/assets/161009266/9af15a62-1b4a-4d37-97c8-93aa3fd178cf">

+ еще вопрос. В разрешении экрана 390px, при клике (не наведении курсора) на блоки остается фиолетовый фон. Это норм?
<img width="441" alt="Снимок экрана 2024-02-27 в 14 56 24" src="https://github.com/Team-Code-Wizards/frontend/assets/161009266/2bd2fa1f-63e3-45e6-b1b2-382ad03e3cee">
<img width="578" alt="Снимок экрана 2024-02-27 в 14 49 54" src="https://github.com/Team-Code-Wizards/frontend/assets/161009266/08ac1653-1d16-4846-bee9-8a1d24bfb545">

2024-02-27 14:53 UTC, darikomarenko commented
Добавила плавный переход.
По этому вопросу: "в разрешении экрана 390px, при клике (не наведении курсора) на блоки остается фиолетовый фон" - это также будет и на 1440, если смотреть через devtools, попробуй глянуть просто сузив окно браузера, там все ок

2024-02-27 17:20 UTC, merged