Feature/interaction
Team-Code-Wizards/frontend pull request #42
Opened 2024-01-14 19:04 UTC by tintinelle

Добавила компонент Interaction для блока "Взаимодействие с нами". Внутри папки Interaction его дочерний компонент Step для карточек с шагами взаимодействия.
![interaction](https://github.com/Team-Code-Wizards/code-wizards/assets/104452692/3f27180b-0389-4650-bc8b-42f4c0b77cc0)

2024-01-15 06:20 UTC, darikomarenko approved these changes

2024-01-15 13:04 UTC, OGSmit requested changes
![Scccc](https://github.com/Team-Code-Wizards/code-wizards/assets/114614095/4261c7e2-603b-49a0-85f4-6903d0c4a999)


Подогнать под PP

2024-01-16 15:33 UTC, tintinelle commented
<img width="569" alt="Снимок экрана 2024-01-16 в 20 28 58" src="https://github.com/Team-Code-Wizards/code-wizards/assets/104452692/41d6d2ac-498b-4498-b278-e6809bd95e9f">
Исправила верстку под PP

2024-01-18 08:38 UTC, OGSmit approved these changes

2024-01-18 14:24 UTC, merged