Feature/contacts component
Team-Code-Wizards/frontend pull request #50
Opened 2024-01-16 14:14 UTC by dableeet

2024-01-16 16:52 UTC, OGSmit requested changes
![cvcvcvcvc](https://github.com/Team-Code-Wizards/code-wizards/assets/114614095/b61b76c3-b612-4c43-9369-9e727f548d5d)

микро расхождения в пределах , так же влей обновленный  develop вместе с ним подтянется padding 80px , который уже работает на скрине выше

2024-01-16 16:52 UTC, OGSmit commented on package.json
> +			"git add"
не нужно изменять package из ветки со своим компонентом

2024-01-18 07:23 UTC, darikomarenko approved these changes

2024-01-18 07:23 UTC, darikomarenko commented on src/images/icons/ArrowIcon.tsx
чисто из интереса и уточнить - иконки должны вот так компонентами быть с расширением tsx?

2024-01-18 08:12 UTC, darikomarenko commented on src/images/icons/ArrowIcon.tsx
> Импорт SVG в качестве компонента React: Преимущества:
> 
> Модульность: SVG компонент можно использовать повторно в различных частях приложения. Манипуляция с помощью React: Вы можете легко внести изменения в SVG с использованием состояния и свойств React. Недостатки:
> 
> Размер файла: Ваше приложение будет занимать больше места из-за кода React, который обрабатывает SVG.
> 
> Использование файла SVG напрямую: Преимущества:
> 
> Простота: Без необходимости создания дополнительного компонента, вы можете использовать SVG напрямую в коде. Недостатки:
> 
> Немодульность: SVG не будет повторно используемым компонентом, что может затруднить его изменение в разных частях приложения.
круто, спасибо!

2024-01-18 08:14 UTC, darikomarenko commented on src/images/icons/ArrowIcon.tsx
спасибо! круто)

2024-01-18 15:23 UTC, JackKerouac1613 approved these changes

2024-01-18 15:29 UTC, EkaterinaYurchyk2022 approved these changes

2024-01-18 15:32 UTC, OGSmit approved these changes

2024-01-18 15:32 UTC, merged