Feature/create stages
Team-Code-Wizards/frontend pull request #52
Opened 2024-01-17 10:29 UTC by sariunar

Добавлен компонент ""этапы создания сайта", стили 
![image](https://github.com/Team-Code-Wizards/code-wizards/assets/90380387/86c00b8b-3572-4266-9201-4f4ff4aa5708)

2024-01-17 13:36 UTC, darikomarenko requested changes
<img width="386" alt="Снимок экрана 2024-01-17 в 16 35 02" src="https://github.com/Team-Code-Wizards/code-wizards/assets/121871839/ee40894e-f328-4e8b-a598-8834b1a3a6c5">
Надо поточнее расположить элемент на картинке. На скрине вверху как на деле, а внизу - как на макете, сильно уехало(

2024-01-19 06:51 UTC, darikomarenko approved these changes
Все круто, я только хотела уточнить по кнопочкам с цифрами и кнопка Следующий этап: у них мб должен быть cursor и какой-то hover?

2024-01-19 11:44 UTC, OGSmit submitted a review, later dismissed

2024-01-19 11:54 UTC, OGSmit commented on src/components/StageCreate/index.tsx
> +					/>
заменить на tsx вариант

2024-01-20 20:10 UTC, EkaterinaYurchyk2022 commented on src/components/StageCreate/style.module.scss
> +        font-family: var(--rg-font);
Добавить для позиционирования посередине и ограничения контента по ширине:
max-width: 1280px;
margin: 0 auto;

2024-01-20 20:11 UTC, EkaterinaYurchyk2022 commented on src/components/StageCreate/style.module.scss
можно спросить у дизайнера, возможно ли сделать фон одной цельной картинкой

2024-01-20 20:18 UTC, EkaterinaYurchyk2022 commented on src/components/StageCreate/style.module.scss
> +    background-image: url(../../images/stage/background.png);
вроде url должен быть строкой...

2024-01-20 20:19 UTC, JackKerouac1613 commented on src/components/StageCreate/style.module.scss
Так там эти иконки меняться будут. Это тип слайдер

2024-01-21 11:29 UTC, darikomarenko commented on src/components/StageCreate/index.tsx
> +import styles from './style.module.scss';
<img width="614" alt="Снимок экрана 2024-01-21 в 14 23 31" src="https://github.com/Team-Code-Wizards/frontend/assets/121871839/5e577665-9ee5-452f-aab3-2c95e4d8f09b">
немного поехали цифры

2024-01-21 11:29 UTC, darikomarenko commented on src/components/StageCreate/index.tsx
> +				<button type="button" className={styles['stage__btn']}>
предлагаю cursor pointer на кнопку Следующий этап

2024-01-21 12:12 UTC, JackKerouac1613 commented on src/components/StageCreate/index.tsx
> +import styles from './style.module.scss';
Хмм, это оч странно, так как у меня вот так
![number](https://github.com/Team-Code-Wizards/frontend/assets/133998734/2dd555fe-c63d-481c-aa18-31cc50a0a98c)

2024-01-21 12:26 UTC, JackKerouac1613 commented on src/components/StageCreate/index.tsx
> +import styles from './style.module.scss';
Я добавил паддинги, на всякий случай

2024-01-21 13:08 UTC, OGSmit approved these changes
можно для кнопок-кружков сделать эффект наведения помимо cursor: pointer , можно уточнить у дизайнера

2024-01-21 14:17 UTC, merged